service: serverlessEmail

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true



functions:
  get:
    handler: handler.handler
    events: 
      - http: 
          method: GET
          path: /users/{name}
